ADD: new custom install layouts
stereum-dev/ethereum-node pull request #1520
Opened 2023-11-01 13:58 UTC by MaxTheGeeek

2023-11-01 16:03 UTC, montajebi approved these changes

2023-11-02 09:17 UTC, NeoPlays requested changes
lgtm otherwise

2023-11-02 09:18 UTC, MaxTheGeeek commented on launcher/src/components/UI/TheCarousel/components/TheCarousel.vue
> +  if (configNetwork.value.id === 1 || configNetwork.value.id === 1) {
let me check

2023-11-02 09:32 UTC, NeoPlays requested changes

2023-11-02 09:32 UTC, NeoPlays commented on launcher/src/components/UI/TheCarousel/components/TheCarousel.vue
>    } else if (configNetwork.value.id === 2 || configNetwork.value.id === 2) {
this goes for all `ifs` tho :sweat_smile:

2023-11-02 09:39 UTC, NeoPlays approved these changes
lgtm

2023-11-02 10:15 UTC, merged