ADD: NodeUpdates.js
stereum-dev/ethereum-node pull request #1695
Opened 2024-02-09 17:07 UTC by M4r71nW

upgrade to Noble Numbat
upgradePackage Function
getUpgradeablePackages Function

2024-02-13 13:28 UTC, NeoPlays requested changes

2024-02-23 11:00 UTC, MaxTheGeeek approved these changes
looks good

2024-02-23 11:05 UTC, MaxTheGeeek approved these changes

2024-02-23 11:06 UTC, MaxTheGeeek approved these changes

2024-02-23 11:08 UTC, MaxTheGeeek approved these changes

2024-02-23 11:28 UTC, NeoPlays approved these changes

2024-02-23 11:39 UTC, merged