FIX: export all logs in the log page
stereum-dev/ethereum-node pull request #1899
Opened 2024-05-29 13:50 UTC by mabasian

2024-05-29 16:47 UTC, NeoPlays requested changes
I don't think all of this duplicated code is needed

2024-05-29 16:48 UTC, NeoPlays reviewed
duplicted code

2024-05-30 08:25 UTC, mabasian commented
@NeoPlays The `updateAndExportAllLogs` and `getAllServiceLogs` functions have been updated to ensure they work with a single button click. Please review the changes when you get a chance.

2024-05-30 08:43 UTC, mabasian commented on launcher/src/components/UI/node-page/NodeScreen.vue
> +  pollingLogs = setInterval(updateAllServiceLogs, 10000); // refresh logs
All the intervals removed related to this func

2024-05-30 08:44 UTC, mabasian commented on launcher/src/backend/Monitoring.js
> +  async getAllServiceLogs(args) {
Function changed

2024-06-03 10:08 UTC, NeoPlays approved these changes
lgtm 🚀

2024-06-03 10:13 UTC, merged