add devnet
stereum-dev/ethereum-node pull request #2014
Opened 2024-08-27 10:13 UTC by gbayasgalan

fix: https://github.com/stereum-dev/ethereum-node/issues/1729

2024-09-25 08:28 UTC, MaxTheGeeek submitted a review, later dismissed
lgtm

2024-11-05 13:10 UTC, NeoPlays requested changes
This was all i could find.
I'm sure i missed something 😅

2024-11-05 13:10 UTC, NeoPlays commented on launcher/src/backend/ethereum-services/GethService.js
> +            "--http.corsdomain=*",
i think you can code this simpler. the configs are almost the same, just remove / add the un/wanted ones

2024-11-05 13:10 UTC, NeoPlays commented on launcher/src/backend/ServiceManager.js
> +                new ServicePort(null, 9090, 9090, servicePortProtocol.tcp),
just push the additional ports if it's devnet. saves code ;)

2024-11-05 13:10 UTC, NeoPlays commented on launcher/src/backend/ethereum-services/PrysmBeaconService.js
> +            `--jwt-secret=${JWTDir}`,
same here

2024-11-19 17:51 UTC, gbayasgalan commented on launcher/src/backend/ServiceManager.js
> +  async writeConfigYaml(writeConfigData) {
The function name is already unique, but I added "Devnet" for better clarity

2024-11-19 18:02 UTC, gbayasgalan commented on controls/roles/initiate-devnet-genesis/tasks/create_genesis.yml
> +    image: gcr.io/prysmaticlabs/prysm/cmd/prysmctl:v5.0.4
This version is specific to the devnet, atm :)

2024-11-19 18:17 UTC, gbayasgalan commented on controls/roles/initiate-devnet-genesis/tasks/create_genesis.yml
> +    image: gcr.io/prysmaticlabs/prysm/cmd/prysmctl:v5.0.4
https://github.com/stereum-dev/ethereum-node/issues/2111

2024-11-20 06:30 UTC, daGscheid commented
Will be only be possible currently with a specific client combination and version after release for now: https://github.com/stereum-dev/ethereum-node/issues/2111

2024-11-20 11:21 UTC, NeoPlays approved these changes
lgtm so far

2024-11-20 11:22 UTC, gbayasgalan commented
> lgtm so far

lets wait meeting tomorrow :)

2024-11-21 13:17 UTC, merged