ADD: Update Scripts and Changes to new Setups
stereum-dev/ethereum-node pull request #2091
Opened 2024-10-09 14:00 UTC by NeoPlays

### Includes:
- Erigon Image Change
- SSV Iamge Change
- Lido Holesky Allowlist Change

2024-10-09 16:13 UTC, daverolo requested changes
Added a comment to the SSV DKG image change

2024-10-10 09:24 UTC, NeoPlays commented on launcher/src/backend/ethereum-services/SSVDKGService.js
> +    const image = "ssvlabs/ssv-dkg";
good point 🙏🏼

2024-10-11 11:37 UTC, daverolo commented on launcher/src/backend/ethereum-services/SSVDKGService.js
> +    const image = "ssvlabs/ssv-dkg";
SSV DKG will get a separate release

2024-10-11 11:41 UTC, daverolo commented
This PR will wait as Draft for the SSV node mainnet release, then:
- Update updates.json to the mainnet version
- Do a Stereum release

2024-10-17 08:16 UTC, gbayasgalan approved these changes

2024-10-17 11:54 UTC, merged

2024-10-17 12:01 UTC, daverolo commented
JFTR: We decided in MM to remove SSV changes and merge the PR. SSV will get a separate Draft by @NeoPlays when we get an effective date for their mainnet release.