Lighthouse monitoring (prometheus, prom-node-exporter and grafana)
stereum-dev/ethereum-node pull request #73
Opened 2022-02-18 11:41 UTC by gbayasgalan

2022-02-18 12:14 UTC, stefa2k requested changes

2022-02-18 13:34 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +    - /opt/app/services/59827650-8ac6-11ec-81ec-f3dc0fb8f30e/grafana/provisioning/datasources
done!

2022-02-18 15:26 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +    src: "{{ role_path }}/files/grafana/provisioning-lh/dashboards/BeaconProcessing.json"
done!

2022-02-18 15:53 UTC, stefa2k requested changes

2022-02-18 15:53 UTC, stefa2k commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +    dest: "{{ grafana_config_path }}/provisioning/datasources"
see comment at line 10

2022-02-18 16:08 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +  when: stereum_service_configuration.command.find("GRAFANA_INI_LH") != -1
Here the `when` is used to determine which consensys client is choosen. The `when` on the `main.yaml` is for grafana service itself

2022-02-18 17:36 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +    dest: "{{ grafana_config_path }}/provisioning/dashboards"
done!

2022-02-18 17:36 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +  when: stereum_service_configuration.command.find("GRAFANA_INI_LH") != -1
done!

2022-02-18 17:37 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +    - "{{ grafana_config_path }}/provisioning/datasources"
done!

2022-02-21 16:50 UTC, gbayasgalan commented on controls/roles/manage-service/tasks/write-grafana-configuration.yml
> +  when: stereum_service_configuration.command.find("GRAFANA_INI_LH") != -1
done!

2022-02-23 23:44 UTC, gbayasgalan commented on controls/roles/manage-service/molecule/monitor-lighthouse/verify.yml
> +      - grafana.stdout.find("HTTP Server Listen") != -1
done!

2022-02-24 08:32 UTC, stefa2k approved these changes
lgtm, great work!

2022-02-24 08:32 UTC, merged